---
kind: pipeline
type: kubernetes
name: default

concurrency:
  limit: 1

environment:
  MISP_TAG: v2.4.187
  MODULES_TAG: v2.4.187
  PHP_VER: 20190902
  REDIS_VER: 7.2.4-alpine
  MARIADB_VER: 10.9.8-jammy

steps:
  - name: build_publish_server
    image: plugins/kaniko
    settings:
      repo: m1nl/misp-server
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      dockerfile: server/Dockerfile
      context: server/
      build_args:
        - MISP_TAG
        - MODULES_TAG
        - PHP_VER
      auto_tag: true

  - name: build_publish_modules
    image: plugins/kaniko
    settings:
      repo: m1nl/misp-modules
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      dockerfile: modules/Dockerfile
      context: modules/
      build_args:
        - MISP_TAG
        - MODULES_TAG
        - PHP_VER
      auto_tag: true

  - name: notify_failure
    image: drillster/drone-email
    settings:
      host:
        from_secret: mail_host
      username:
        from_secret: mail_username
      password:
        from_secret: mail_password
      from:
        from_secret: drone_sender
      recipients:
        from_secret: drone_recipients
      recipients_only: true
    when:
      status:
      - failure
---
kind: signature
hmac: 8e8e570a39b8620034e78c18417ba0e2bead8e0b1dd5f679e32e6179f884739f

...
